include:
  - project: 'new_dbo_le/infra/ci-templates'
    ref: main
    file: '/dbo-ci-manifest.yml'

variables:
  SERVICE_NAME: "credit-fabric-remote"
  PORT: "80"
  NS_NAME: "sme"
  TARGET_ENV: "dev"
  # нестандартный путь образа и раннер (проект вне new_dbo_le)
  IMAGE_REPO_PATH: "loan-processing/credit-fabric-remote"
  RUNNER_TAG: "my-runner"
  # маппинг кредов registry на переменные этого проекта
  EXT_REGISTORY_NEW: "docker-new-dbo-nexus.hamkorbank.uz"
  EXT_REGISTORY_NEW_US: "$NEXUS_USER"
  EXT_REGISTORY_NEW_PW: "$NEXUS_PASSWORD"