server {
    listen 80;
    listen [::]:80;

    server_name localhost;

    include /etc/nginx/mime.types;

    types {
        application/javascript mjs;
    }

    location /sme-kk-js/ {
        alias /usr/share/nginx/html/;
        index index.html;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Origin, Content-Type, Accept, Authorization" always;

        try_files $uri $uri/ /sme-kk-js/index.html;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
