import { CUSTOM_ICONS_TYPE } from "src/app/shared/types";

export const SVG_ICONS: { [key in string]: CUSTOM_ICONS_TYPE } = {
  html: 'hamkor_html',
  word: 'hamkor_word',
  pdf: 'hamkor_pdf',
  txt: 'hamkor_txt',
  xls: 'hamkor_xls',
  excel: 'hamkor_excel',
  csv: 'hamkor_csv',
  refresh: 'hamkor_refresh',
  mail: 'hamkor_mail',
  share: 'hamkor_share',
  delete: "hamkor_delete",
  template: "hamkor_template",
  done_badge: 'hamkor_done_badge',
  arrowBottom: 'hamkor_arrow_bottom',
  blocked: 'hamkor_blocked',
  copy: 'hamkor_copy',
  edit: 'hamkor_edit',
  save: 'hamkor_save',
  subscribe_pen: 'hamkor_subscribe_pen',
  reverse: 'hamkor_reverse_right',
  calendarCheck02: 'hamkor_calendar-check-02',
  subscribePenTwo: 'hamkor_subscribe_pen2',
  phone: 'hamkor_phone',
  briefcase01: 'hamkor_briefcase-01',
  setting: 'hamkor_setting',
  logout03: 'hamkor_logout-03',
  blockOutline: 'hamkor_blocked_outline',
  comment: 'hamkor_comment',
  accountHideDots:'hamkor_account-hide-dots',
  dotsVertical:'hamkor_dots-vertical',
  trashFull:'hamkor_trash-full',
  filter:'hamkor_filter',
  calendar:'hamkor_calendar',
  download:'hamkor_download',
  switchVertical:'hamkor_switch_vertical',
  notification:'hamkor_notification',
  printer:'hamkor_printer',
  spinner:'hamkor_spinner',
  minimize:'hamkor_minimize',
  pendingClock:"hamkor_pending_clock",
  errorAttention:'hamkor_error_attention',
  editSign:'hamkor_edit_sign',
  doneSuccess:'hamkor_done_success',
  uploadTopup:'hamkor_upload_2',
  depositOutline:'hamkor_deposit_outline',
  paper:'hamkor_paper',
  calendarFull:'hamkor_calendar_full',
  downloadRounded:"hamkor_download_rounded",
  uploadTwo:'hamkor_upload_02',
  fileSix:'hamkor_file_06',
  filePlus02:'hamkor_file_plus_02',
  hamkorInfoCircle:'hamkor_info_circle',
  cancel:'hamkor_cancel'
};
