export const environment = {
  coreUrl: 'https://intcorp-dev.hamkorbank.uz/sme-kk/api/v1/core-sme/',
  losUrl: 'https://intcorp-dev.hamkorbank.uz/sme-kk/api/v1/los-sme/',
  handbookUrl: 'https://intcorp-dev.hamkorbank.uz/sme-kk/handbooks/api/v1/los-sme/',
  apiKey: 'eyJvcmciOiIxIiwiaWQiOiIzMWUyY2U2ZmI0YzQ0OGE3ODg0NzE5ZmU4ZWQ1MjI4NSIsImgiOiJzaGEyNTYifQ==',
  ablePlatform: 'los-sme',
  projectTag: 'kk-sme',
  deviceType: 'Android',
  user: {
    pinfl: '',
    phone: '',
    email: '',
    name: '',
    theme: '',
    lon: 0,
    lat: 0,
    language: '',
  },
  dev: false,
};
