export const environment = {
  coreUrl: 'https://intcorp-dev.hamkorbank.uz/sme-kk/api/v1/core-sme/',
  losUrl: 'https://intcorp-dev.hamkorbank.uz/sme-kk/api/v1/los-sme/',
  handbookUrl: 'https://intcorp-dev.hamkorbank.uz/sme-kk/handbooks/api/v1/los-sme/',
  ablePlatform: 'los-sme',
  projectTag: 'kk-sme',
  deviceType: 'vebview',
  appVersion: '99.99.99',
  deviceRoot: '0',
  mode: 'testing',
  user: {
    pinfl: '52001016860016',
    phone: '990031497',
    email: 'o.rixsimboyev@hamkorbank.uz',
    name: 'YATT QOSIMOV UMID',
    clientId: 962909,
    clientUid: 351594,
    inn: 302638303,
    theme: 'dark',
    lon: 0,
    lat: 0,
    language: 'ru',
  },
};
