include:
  - project: 'new_dbo_le/infra/ci-templates'
    ref: main
    file: '/dbo-ci-manifest.yml'

variables:
  SERVICE_NAME: "corp-client-web"
  PORT: "80"
  NS_NAME: "hamkorbank"
  TARGET_ENV: "dev"
