apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
  namespace: NS_NAME
  labels:
    app: SERVICE_NAME

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 3
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      values:
                        - SERVICE_NAME
                      operator: In
      containers:
        - name: SERVICE_NAME
          image: DOCKER_IMAGE
          env:
            - name: TO
              value: 'BAR'
      #          resources:
      #            limits:
      #              cpu: '5000m'
      #              memory: '1Gi'
      #            requests:
      #              cpu: '500m'
      #              memory: '512Mi'
      imagePullSecrets:
        - name: registry-key
      serviceAccountName: api-reader
    metadata:
      labels:
        app: SERVICE_NAME

---

apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: NS_NAME
  labels:
    app: SERVICE_NAME
spec:
  type: NodePort
  selector:
    app: SERVICE_NAME
  ports:
    - protocol: TCP
      port:  PORT
      targetPort: PORT

