export type CUSTOM_ICONS_TYPE =
  'hamkor_pdf'
  | 'hamkor_html'
  | 'hamkor_word'
  | 'hamkor_txt'
  | 'hamkor_csv'
  | 'hamkor_xls'
  | 'hamkor_excel'
  | 'hamkor_refresh'
  | 'hamkor_share'
  | 'hamkor_mail'
  | 'hamkor_delete'
  | 'hamkor_done_badge'
  | 'hamkor_arrow_bottom'
  | 'hamkor_blocked'
  | 'hamkor_copy'
  | 'hamkor_edit'
  | 'hamkor_save'
  | 'hamkor_subscribe_pen'
  | 'hamkor_reverse_right'
  | 'hamkor_template'
  | 'hamkor_calendar-check-02'
  | 'hamkor_subscribe_pen2'
  | 'hamkor_phone'
  | 'hamkor_briefcase-01'
  | 'hamkor_setting'
  | 'hamkor_logout-03'
  | 'hamkor_blocked_outline'
  | 'hamkor_comment'
  |'hamkor_account-hide-dots'
  | 'hamkor_dots-vertical'
  | 'hamkor_trash-full'
  |'hamkor_filter'
  |'hamkor_calendar'
  |'hamkor_download'
  |'hamkor_switch_vertical'
  |'hamkor_notification'
  |'hamkor_printer'
  |'hamkor_spinner'
  |'hamkor_minimize'
  |'hamkor_pending_clock'
  |'hamkor_error_attention'
  |'hamkor_edit_sign'
  |'hamkor_done_success'
  |'hamkor_upload_2'
  |'hamkor_deposit_outline'
  |'hamkor_paper'
  |'hamkor_calendar_full'
  |'hamkor_download_rounded'
  | 'hamkor_upload_02'
  |'hamkor_file_06'
  |'hamkor_file_plus_02'
  |'hamkor_info_circle'
  |'hamkor_cancel'

export type MAT_ICONS_TYPE =
  | 'more_vert'
  | 'expand_more'
  | 'close'
  | 'calendar_today'
  | 'translate'
  | 'settings'
  | 'add_circle'
  | 'apps'
  | 'edit'
  | 'delete'
  | 'logout'
  | 'visibility'
  | 'person'
  | 'menu_book'
  | 'description'
  | 'file_download'
  | 'arrow_forward'
  | 'help_outline'
  | 'info'
  | 'search'
  | 'assignment'
  | 'insert_drive_file'
  | 'person_add'
  | 'access_time'
  | 'schedule'
  | 'download'
  | 'work'

export type ICONS_TYPE = CUSTOM_ICONS_TYPE | MAT_ICONS_TYPE;
